services:
  srv_bunkerweb:
    hostname: srv_bunkerweb
    image:   bunkerity/bunkerweb-all-in-one:1.6.6
    restart: no
    container_name: srv_bunkerweb
    cap_add: [ "NET_ADMIN" ]
    network_mode: host
    volumes:
      - ./srv_bunkerweb/conf:/etc/bunkerweb
      - ./srv_bunkerweb/data:/var/lib/bunkerweb
    dns: [ $SUBNET_SERVERS.$DNS_SRV_IP ]